WARNING 2017-03-10 16:49:33,331: elasticsearch: log_request_fail: 94: HEAD http://localhost:9200/tweets [status:N/A request:0.005s]: ('HEAD', u'http://localhost:9200/tweets', 'N/A', 0.00489497184753418)
Traceback (most recent call last):
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 75, in perform_request
    timeout=timeout or self.timeout)
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /tweets (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9b6e349050>: Failed to establish a new connection: [Errno 111] Connection refused',))
WARNING 2017-03-10 16:49:33,339: elasticsearch: log_request_fail: 94: HEAD http://localhost:9200/tweets [status:N/A request:0.002s]: ('HEAD', u'http://localhost:9200/tweets', 'N/A', 0.0022649765014648438)
Traceback (most recent call last):
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 75, in perform_request
    timeout=timeout or self.timeout)
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /tweets (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9b6e35bd50>: Failed to establish a new connection: [Errno 111] Connection refused',))
WARNING 2017-03-10 16:49:33,342: elasticsearch: log_request_fail: 94: HEAD http://localhost:9200/tweets [status:N/A request:0.002s]: ('HEAD', u'http://localhost:9200/tweets', 'N/A', 0.0019850730895996094)
Traceback (most recent call last):
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 75, in perform_request
    timeout=timeout or self.timeout)
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /tweets (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9b6e35be50>: Failed to establish a new connection: [Errno 111] Connection refused',))
WARNING 2017-03-10 16:49:33,344: elasticsearch: log_request_fail: 94: HEAD http://localhost:9200/tweets [status:N/A request:0.002s]: ('HEAD', u'http://localhost:9200/tweets', 'N/A', 0.002029895782470703)
Traceback (most recent call last):
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 75, in perform_request
    timeout=timeout or self.timeout)
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/fartash/anaconda3/envs/Etl-boilerplate/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9200): Max retries exceeded with url: /tweets (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9b6e35bcd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
INFO 2017-03-10 16:52:12,051: elasticsearch: log_request_success: 80: PUT http://localhost:9200/tweets [status:200 request:0.130s]: ('PUT', u'http://localhost:9200/tweets', 200, 0.12992382049560547)
INFO 2017-03-10 16:53:26,741: elasticsearch: log_request_success: 80: HEAD http://localhost:9200/tweets [status:200 request:0.009s]: ('HEAD', u'http://localhost:9200/tweets', 200, 0.00943613052368164)
INFO 2017-03-10 16:54:44,449: elasticsearch: log_request_success: 80: HEAD http://localhost:9200/tweets [status:200 request:0.008s]: ('HEAD', u'http://localhost:9200/tweets', 200, 0.007775068283081055)
INFO 2017-03-10 16:58:26,026: elasticsearch: log_request_success: 80: HEAD http://localhost:9200/tweets [status:200 request:0.010s]: ('HEAD', u'http://localhost:9200/tweets', 200, 0.010493993759155273)
INFO 2017-03-10 16:58:45,044: elasticsearch: log_request_success: 80: HEAD http://localhost:9200/tweets [status:200 request:0.009s]: ('HEAD', u'http://localhost:9200/tweets', 200, 0.009272098541259766)
INFO 2017-03-10 16:59:27,364: elasticsearch: log_request_success: 80: HEAD http://localhost:9200/tweets [status:200 request:0.020s]: ('HEAD', u'http://localhost:9200/tweets', 200, 0.020184993743896484)
INFO 2017-03-10 17:00:28,088: elasticsearch: log_request_success: 80: HEAD http://localhost:9200/tweets [status:200 request:0.016s]: ('HEAD', u'http://localhost:9200/tweets', 200, 0.015730857849121094)
WARNING 2017-03-10 17:00:28,711: elasticsearch: log_request_fail: 94: POST http://localhost:9200/tweets/tweet [status:400 request:0.051s]: (u'POST', u'http://localhost:9200/tweets/tweet', 400, 0.050642967224121094)
INFO 2017-03-10 17:01:40,536: elasticsearch: log_request_success: 80: PUT http://localhost:9200/tweets [status:200 request:0.107s]: ('PUT', u'http://localhost:9200/tweets', 200, 0.10725021362304688)
INFO 2017-03-10 17:01:40,628: elasticsearch: log_request_success: 80: PUT http://localhost:9200/tweets/_mapping/tweet [status:200 request:0.089s]: ('PUT', u'http://localhost:9200/tweets/_mapping/tweet', 200, 0.08862090110778809)
INFO 2017-03-10 17:01:53,106: elasticsearch: log_request_success: 80: HEAD http://localhost:9200/tweets [status:200 request:0.020s]: ('HEAD', u'http://localhost:9200/tweets', 200, 0.01967597007751465)
INFO 2017-03-10 17:02:02,455: elasticsearch: log_request_success: 80: POST http://localhost:9200/tweets/tweet [status:201 request:0.165s]: (u'POST', u'http://localhost:9200/tweets/tweet', 201, 0.16475915908813477)
INFO 2017-03-10 17:04:13,726: elasticsearch: log_request_success: 80: PUT http://localhost:9200/tweets [status:200 request:0.124s]: ('PUT', u'http://localhost:9200/tweets', 200, 0.12434005737304688)
INFO 2017-03-10 17:04:13,828: elasticsearch: log_request_success: 80: PUT http://localhost:9200/tweets/_mapping/tweet [status:200 request:0.100s]: ('PUT', u'http://localhost:9200/tweets/_mapping/tweet', 200, 0.10013580322265625)
INFO 2017-03-10 17:04:30,219: elasticsearch: log_request_success: 80: HEAD http://localhost:9200/tweets [status:200 request:0.020s]: ('HEAD', u'http://localhost:9200/tweets', 200, 0.020413875579833984)
INFO 2017-03-10 17:04:30,870: elasticsearch: log_request_success: 80: POST http://localhost:9200/tweets/tweet [status:201 request:0.035s]: (u'POST', u'http://localhost:9200/tweets/tweet', 201, 0.03470492362976074)
